language: python
sudo: false

python:
  - '3.6'
  
install:
  - pip install -r requirements.txt
  - pip install python-coveralls
  
script:
  - pytest

after_success:
  - coverage report
  - coveralls
