language: python
sudo: false

python:
  - '3.6'
  
install:
  - pip install -r requirements.txt
  - pip install python-coveralls
  - pip install pytest-cov
  - pip install coveralls
  
script:
  - pytest --cov=optimol/
  
after_success:
  - coverage report
  - coveralls
