language: python
sudo: false

python:
  - '3.6'
  
install:
  - pip install -r requirements.txt
  - pip install python-coveralls
  - pip install coveralls
  
script:
  - pytest
  - coverage run --source=mypkg setup.py test

after_success:
  - coverage report
  - coveralls
