name: OptiMol
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - ca-certificates=2020.1.1
  - certifi=2019.11.28
  - ld_impl_linux-64=2.33.1
  - libedit=3.1.20181209
  - libffi=3.2.1
  - libgcc-ng=9.1.0
  - libstdcxx-ng=9.1.0
  - ncurses=6.2
  - openssl=1.1.1
  - pip=20.0.2
  - python=3.8.1
  - readline=7.0
  - setuptools=46.0.0
  - sqlite=3.31.1
  - tk=8.6.8
  - wheel=0.34.2
  - xz=5.2.4
  - zlib=1.2.11
  - pip:
    - joblib==0.14.1
    - numpy==1.18.1
    - pandas==1.0.1
    - python-dateutil==2.8.1
    - pytz==2019.3
    - scikit-learn==0.22.2.post1
    - scipy==1.4.1
    - six==1.14.0
    - sklearn==0.0
    - xgboost==1.0.2

